version: '2'
services:
  api:
    container_name: bodify-api
    image: node:7.7-slim
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    links:
      - mongodb
    working_dir: /app
    command: ./node_modules/.bin/nodemon src/index.js
  mongodb:
    container_name: bodify-mongodb
    image: mongo:3.4
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
